const SUPABASE_URL='https://nfxgifqgohcclmpsktqj.supabase.co';
const SUPABASE_KEY=window.NFM_SUPABASE_KEY||'';
const db=(window.supabase&&SUPABASE_KEY)?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
const LOGIN_USER='nfm2019',LOGIN_PASS='nfm2019*nfm2019',BUCKET='expense-bills';
const categories=['Employee Salary','Godown Rent','Vehicle Maintenance','Fuel','EB Bills','Chit Fund','Loan EMI','Other'];
let expenses=[],plan={id:'plans',loan_total:0,loan_paid:0,chit_total:0,chit_paid:0},selectedBillFile=null;
const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2}),today=()=>new Date().toISOString().slice(0,10);
function show(id,v){const e=$(id);if(e)e.classList.toggle('hidden',!v)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m,bad=false){const e=$('toast');if(!e)return;e.textContent=m;e.className='toast show '+(bad?'error-toast':'');setTimeout(()=>e.className='toast',2800)}
function status(t,on=false){const e=$('cloudStatus');if(!e)return;e.textContent=t;e.className='status '+(on?'online':'offline')}
$('loginForm').onsubmit=e=>{e.preventDefault();$('loginError').textContent='';if($('username').value.trim()===LOGIN_USER&&$('password').value===LOGIN_PASS){if($('remember').checked)localStorage.setItem('nfm_logged_in','1');else localStorage.removeItem('nfm_logged_in');openApp()}else $('loginError').textContent='Incorrect username or password.'};
$('logoutBtn').onclick=()=>{localStorage.removeItem('nfm_logged_in');show('appView',false);show('loginView',true)};
function openApp(){show('loginView',false);show('appView',true);if($('expenseDate'))$('expenseDate').value=today();loadAll()}
if(localStorage.getItem('nfm_logged_in')==='1')openApp();
async function loadAll(){if(!db){status('Cloud unavailable');toast('Supabase could not be initialized. Check the connection.',true);return}status('Syncing…');try{const [a,b]=await Promise.all([db.from('expenses').select('*').order('expense_date',{ascending:false}).order('id',{ascending:false}),db.from('payment_plans').select('*').eq('id','plans').maybeSingle()]);if(a.error)throw a.error;if(b.error)throw b.error;expenses=a.data||[];if(b.data)plan=b.data;status('Cloud synced',true);renderAll()}catch(e){status('Cloud error');toast('Cloud connection failed: '+e.message,true)}}
function renderAll(){const n=new Date(),y=n.getFullYear(),m=n.getMonth(),cur=expenses.filter(x=>{let d=new Date(x.expense_date+'T00:00:00');return d.getFullYear()===y&&d.getMonth()===m}),p=new Date(y,m-1,1),prev=expenses.filter(x=>{let d=new Date(x.expense_date+'T00:00:00');return d.getFullYear()===p.getFullYear()&&d.getMonth()===p.getMonth()}),total=expenses.reduce((a,x)=>a+Number(x.amount),0),cm=cur.reduce((a,x)=>a+Number(x.amount),0),pm=prev.reduce((a,x)=>a+Number(x.amount),0);$('dashboardMonth').textContent=n.toLocaleString('en-IN',{month:'long',year:'numeric'});$('totalExpense').textContent=money(total);$('monthlyExpense').textContent=money(cm);if(pm){let r=cm/pm*100,c=(cm-pm)/pm*100;$('momRatio').textContent=r.toFixed(1)+'%';$('momChange').textContent=(c>=0?'↑ ':'↓ ')+Math.abs(c).toFixed(1)+'% vs previous month'}else{$('momRatio').textContent='—';$('momChange').textContent='No previous month data'}let bud=Number(localStorage.getItem('nfm_budget')||0);$('remainingBudget').textContent=bud?money(bud-cm):'₹0';$('budgetHint').textContent=bud?'Budget '+money(bud):'Set budget below';renderTrend();renderCats();renderTable('recentExpenses',expenses.slice(0,8));renderTable('expenseTable',expenses);renderPlans()}
function renderTrend(){let n=new Date(),a=[];for(let i=5;i>=0;i--){let d=new Date(n.getFullYear(),n.getMonth()-i,1),v=expenses.filter(x=>{let e=new Date(x.expense_date+'T00:00:00');return e.getFullYear()===d.getFullYear()&&e.getMonth()===d.getMonth()}).reduce((s,x)=>s+Number(x.amount),0);a.push({l:d.toLocaleString('en-IN',{month:'short'}),v})}let max=Math.max(...a.map(x=>x.v),1);$('monthlyTrend').innerHTML=a.map(x=>`<div class="bar-item"><span>${x.l}</span><div class="bar"><i style="height:${Math.max(4,x.v/max*100)}%"></i></div><b>${money(x.v)}</b></div>`).join('')}
function renderCats(){let s={};expenses.forEach(x=>s[x.category]=(s[x.category]||0)+Number(x.amount));let t=Object.values(s).reduce((a,b)=>a+b,0)||1;$('categoryBreakdown').innerHTML=Object.entries(s).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="cat-row"><span>${esc(k)}</span><b>${money(v)}</b><small>${(v/t*100).toFixed(1)}%</small></div>`).join('')||'<div class="muted">No expenses yet.</div>'}
function renderTable(id,rows){$(id).innerHTML=rows.length?`<table><thead><tr><th>Date</th><th>Category</th><th>Amount</th><th>Bill</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.expense_date)}</td><td>${esc(x.category)}</td><td>${money(x.amount)}</td><td>${x.bill?`<a href="${esc(x.bill)}" target="_blank">View</a>`:'—'}</td><td><button class="small" onclick="editExpense(${x.id})">Edit</button> <button class="small danger" onclick="deleteExpense(${x.id})">Delete</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No expenses found.</div>'}
function renderPlans(){[['loanTotal','loan_total'],['loanPaid','loan_paid'],['chitTotal','chit_total'],['chitPaid','chit_paid']].forEach(([a,b])=>$(a).value=Number(plan[b]||0));let lr=Math.max(0,Number(plan.loan_total)-Number(plan.loan_paid)),cr=Math.max(0,Number(plan.chit_total)-Number(plan.chit_paid));$('loanRemaining').textContent='Remaining '+money(lr);$('chitRemaining').textContent='Remaining '+money(cr);$('loanProgress').style.width=(plan.loan_total?Math.min(100,plan.loan_paid/plan.loan_total*100):0)+'%';$('chitProgress').style.width=(plan.chit_total?Math.min(100,plan.chit_paid/plan.chit_total*100):0)+'%';$('monthlyBudget').value=localStorage.getItem('nfm_budget')||''}
$('savePlansBtn').onclick=async()=>{if(!db){toast('Cloud is not connected.',true);return}let n={id:'plans',loan_total:Number($('loanTotal').value||0),loan_paid:Number($('loanPaid').value||0),chit_total:Number($('chitTotal').value||0),chit_paid:Number($('chitPaid').value||0),updated_at:new Date().toISOString()},r=await db.from('payment_plans').upsert(n,{onConflict:'id'});if(r.error){toast('Could not save plan: '+r.error.message,true);return}localStorage.setItem('nfm_budget',$('monthlyBudget').value||'');toast('Payment plan saved.');loadAll()};$('monthlyBudget').onchange=()=>{localStorage.setItem('nfm_budget',$('monthlyBudget').value||'');renderAll()};
function resetBillPicker(){selectedBillFile=null;$('billCamera').value='';$('billFile').value='';$('selectedBill').textContent='No new bill selected.'}
function setSelectedBill(file){selectedBillFile=file||null;$('selectedBill').textContent=file?`Selected: ${file.name}`:'No new bill selected.'}
$('billCamera').onchange=e=>setSelectedBill(e.target.files[0]);
$('billFile').onchange=e=>setSelectedBill(e.target.files[0]);
function openExpense(x=null){$('expenseForm').reset();resetBillPicker();$('expenseId').value=x?.id||'';$('modalTitle').textContent=x?'Edit Expense':'Add Expense';$('amount').value=x?.amount||'';$('category').value=x?.category||categories[0];$('expenseDate').value=x?.expense_date||today();$('existingBill').innerHTML=x?.bill?`Existing bill: <a href="${esc(x.bill)}" target="_blank">View</a>`:'';$('expenseError').textContent='';show('expenseModal',true)}
$('addExpenseBtn').onclick=()=>openExpense();$('closeModal').onclick=()=>show('expenseModal',false);$('expenseModal').onclick=e=>{if(e.target.id==='expenseModal')show('expenseModal',false)};
$('expenseForm').onsubmit=async e=>{e.preventDefault();if(!db){$('expenseError').textContent='Cloud is not connected.';toast('Cloud is not connected.',true);return}$('expenseError').textContent='';let id=$('expenseId').value,file=selectedBillFile,bill=expenses.find(x=>String(x.id)===String(id))?.bill||null;try{if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Use JPG, PNG or WEBP.');if(file.size>8*1024*1024)throw Error('Image must be below 8 MB.');let path=Date.now()+'-'+Math.random().toString(36).slice(2)+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),u=await db.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(u.error)throw u.error;bill=db.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}let payload={amount:Number($('amount').value),category:$('category').value,expense_date:$('expenseDate').value,bill},r=id?await db.from('expenses').update(payload).eq('id',id):await db.from('expenses').insert(payload);if(r.error)throw r.error;show('expenseModal',false);toast('Expense saved to cloud.');loadAll()}catch(err){$('expenseError').textContent='Save failed: '+err.message;toast('Save failed. Nothing was marked as saved.',true)}};
window.editExpense=id=>openExpense(expenses.find(x=>x.id===id));window.deleteExpense=async id=>{if(!db){toast('Cloud is not connected.',true);return}if(!confirm('Delete this expense?'))return;let r=await db.from('expenses').delete().eq('id',id);if(r.error){toast('Delete failed: '+r.error.message,true);return}toast('Expense deleted.');loadAll()};
function go(p){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active-page',x.id===p+'Page'))}document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>go(x.dataset.page));document.querySelectorAll('[data-page-link]').forEach(x=>x.onclick=()=>go(x.dataset.pageLink));$('refreshBtn').onclick=loadAll;
