-- NFM Expense / PERSONAL LEDGER
-- Run in Supabase SQL Editor if you need to recreate the database.
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  amount numeric not null check (amount >= 0),
  category text not null,
  expense_date date not null,
  bill text,
  created_at timestamptz not null default now()
);
create table if not exists public.payment_plans (
  id text primary key,
  loan_total numeric not null default 0,
  loan_paid numeric not null default 0,
  chit_total numeric not null default 0,
  chit_paid numeric not null default 0,
  monthly_budget numeric not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.payment_plans(id) values('plans') on conflict(id) do nothing;
alter table public.expenses enable row level security;
alter table public.payment_plans enable row level security;
create policy "anon_select_expenses" on public.expenses for select to anon using(true);
create policy "anon_insert_expenses" on public.expenses for insert to anon with check(true);
create policy "anon_update_expenses" on public.expenses for update to anon using(true) with check(true);
create policy "anon_delete_expenses" on public.expenses for delete to anon using(true);
create policy "anon_select_payment_plans" on public.payment_plans for select to anon using(true);
create policy "anon_insert_payment_plans" on public.payment_plans for insert to anon with check(true);
create policy "anon_update_payment_plans" on public.payment_plans for update to anon using(true) with check(true);
create policy "anon_delete_payment_plans" on public.payment_plans for delete to anon using(true);
grant select,insert,update,delete on public.expenses to anon;
grant select,insert,update,delete on public.payment_plans to anon;
grant usage,select on sequence public.expenses_id_seq to anon;

-- Storage setup (run separately in SQL Editor if needed):
insert into storage.buckets(id,name,public) values('expense-bills','expense-bills',true) on conflict(id) do update set public=true;
create policy "anon_read_expense_bills" on storage.objects for select to anon using(bucket_id='expense-bills');
create policy "anon_insert_expense_bills" on storage.objects for insert to anon with check(bucket_id='expense-bills');
create policy "anon_update_expense_bills" on storage.objects for update to anon using(bucket_id='expense-bills') with check(bucket_id='expense-bills');
create policy "anon_delete_expense_bills" on storage.objects for delete to anon using(bucket_id='expense-bills');
